export {
  DialogBackdrop as Backdrop,
  DialogCloseButton as CloseButton,
  DialogContent as Content,
  DialogDescription as Description,
  DialogPositioner as Positioner,
  DialogRoot as Root,
  DialogTitle as Title,
  DialogTrigger as Trigger,
  type DialogBackdropProps as BackdropProps,
  type DialogCloseButtonProps as CloseButtonProps,
  type DialogContentProps as ContentProps,
  type DialogDescriptionProps as DescriptionProps,
  type DialogPositionerProps as PositionerProps,
  type DialogRootProps as RootProps,
  type DialogTitleProps as TitleProps,
  type DialogTriggerProps as TriggerProps,
} from "./Dialog";
